default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/ambv/black
    rev: "22.1.0"
    hooks:
    - id: black
-   repo: https://github.com/timothycrosley/isort
    rev: "5.10.1"
    hooks:
    - id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
    - id: flake8
-   repo: https://github.com/PyCQA/pylint
    rev: "v2.12.2"
    hooks:
    - id: pylint
      exclude: core/__init__.py
