"""empty message

Revision ID: b91b24885e63
Revises: e3184b347e6c
Create Date: 2022-02-26 21:41:42.415701

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b91b24885e63"
down_revision = "e3184b347e6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("diary", sa.Column("category_id", sa.Integer(), nullable=True))
    op.drop_constraint("diary_category_topic_key", "diary", type_="unique")
    op.create_unique_constraint(None, "diary", ["category_id", "topic"])
    op.drop_constraint("diary_note_fkey", "diary", type_="foreignkey")
    op.drop_constraint("diary_category_fkey", "diary", type_="foreignkey")
    op.create_foreign_key(
        None, "diary", "category", ["category_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_column("diary", "category")
    op.drop_column("diary", "note")
    op.add_column("note", sa.Column("diary_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "note", "diary", ["diary_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "note", type_="foreignkey")
    op.drop_column("note", "diary_id")
    op.add_column(
        "diary", sa.Column("note", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "diary", sa.Column("category", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "diary", type_="foreignkey")
    op.create_foreign_key(
        "diary_category_fkey",
        "diary",
        "category",
        ["category"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "diary_note_fkey", "diary", "note", ["note"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(None, "diary", type_="unique")
    op.create_unique_constraint(
        "diary_category_topic_key", "diary", ["category", "topic"]
    )
    op.drop_column("diary", "category_id")
    # ### end Alembic commands ###
